sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Actual inlet fan step"
    id: nilan_actual_inlet_fan_step
    accuracy_decimals: 0
    register_type: read
    address: 1101
