sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Actual exhaust fan step"
    id: nilan_actual_exhaust_fan_step
    accuracy_decimals: 0
    register_type: read
    address: 1102   
    icon: mdi:fan
