sensor:
  - platform: modbus_controller
    modbus_controller_id: nilan_modbus_controller
    name: "Actual value for controlled temperature"
    id: nilan_temp_control
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: temperature
    value_type: S_WORD
    register_type: read
    address: 1202
    filters:
      - multiply: 0.01